FROM alpine:3.14
#ADD entrypoint.sh /entrypoint.sh

RUN apk update \
    && apk upgrade \
    && adduser -S phpuser \
    && apk add bash php7 php7-fpm php7-ctype php7-curl php7-dom php7-gd php7-iconv php7-json php7-xml php7-mbstring php7-openssl php7-posix php7-session php7-simplexml php7-xmlreader php7-xmlwriter php7-zip php7-zlib php7-pdo_pgsql php7-fileinfo php7-bz2 php7-intl php7-exif

USER phpuser

ADD php-fpm.conf /etc/php7/php-fpm.conf
ADD www.conf /etc/php7/php-fpm.d/www.conf

EXPOSE 9000

ENTRYPOINT ["/bin/bash"]
CMD ["-c", "/usr/sbin/php-fpm7"]
